### ISSUE TITLE
Invalid Character message after applying script

### ISSUE THREAD

**Issue by ghost** [malyw/fish-shell-the-missing-config#1]
Hello,

After I applied the script I receive an "Invalid Character ' ' in variable name" message. 
`set: Invalid character ' ' in variable name. Only alphanumerical characters and underscores are valid in a variable name.
~/.config/fish/config.fish (line 46): 			set -xg $var $value
                                      			^
from sourcing file ~/.config/fish/config.fish
	called during startup`

I believe this is due to the following line in my _bash_profile_:
`export M2_HOME=/opt/homebrew/Cellar/maven/3.3.9/libexec` 
I think the export statement is not quite parsed.

Can this be solved?

**Comment by shospodarets** [comment]
Thanks for reporting.
It appeared the problem was in missed check of the numerical symbols.
Try using the updated version.
